using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// Drives the Settings panel: binds sliders/dropdowns/toggles to GameSettings,
/// applies changes live, and persists them. Lives on the SettingsPanel root
/// generated by Tools > Medieval Survival > Build Settings Panel.
/// </summary>
public class SettingsPanelUI : MonoBehaviour
{
    [Header("Audio")]
    [SerializeField] private Slider masterVolumeSlider;
    [SerializeField] private TextMeshProUGUI masterVolumeValueText;
    [SerializeField] private Slider musicVolumeSlider;
    [SerializeField] private TextMeshProUGUI musicVolumeValueText;
    [SerializeField] private Slider sfxVolumeSlider;
    [SerializeField] private TextMeshProUGUI sfxVolumeValueText;

    [Header("Graphics")]
    [SerializeField] private TMP_Dropdown qualityDropdown;
    [SerializeField] private TMP_Dropdown resolutionDropdown;
    [SerializeField] private Toggle fullscreenToggle;

    [Header("Controls")]
    [SerializeField] private Slider sensitivitySlider;
    [SerializeField] private TextMeshProUGUI sensitivityValueText;
    [SerializeField] private Toggle invertYToggle;

    [Header("Buttons")]
    [SerializeField] private Button backButton;
    [SerializeField] private Button restoreDefaultsButton;

    [Header("Panels to toggle on Back")]
    [SerializeField] private GameObject settingsPanelRoot;
    [SerializeField] private GameObject mainButtonsPanel;

    // Curated list instead of Screen.resolutions - keeps the dropdown short and organized
    // by aspect ratio instead of dumping every mode the display driver reports.
    private static readonly (int width, int height, string aspect)[] PresetResolutions =
    {
        (2560, 1440, "16:9"),
        (1920, 1080, "16:9"),
        (1366, 768, "16:9"),
        (1280, 720, "16:9"),
        (1920, 1200, "16:10"),
        (1680, 1050, "16:10"),
        (1440, 900, "16:10"),
        (1280, 800, "16:10"),
        (1024, 768, "4:3"),
        (800, 600, "4:3"),
        (640, 480, "4:3"),
    };

    private List<(int width, int height)> _resolutions;
    private bool _suppressCallbacks;

    private void OnEnable()
    {
        BuildQualityOptions();
        BuildResolutionOptions();
        RefreshFromGameSettings();
        WireEvents();
    }

    private void WireEvents()
    {
        // Remove-then-add so OnEnable can safely run more than once without double-firing.
        masterVolumeSlider?.onValueChanged.RemoveListener(OnMasterChanged);
        masterVolumeSlider?.onValueChanged.AddListener(OnMasterChanged);

        musicVolumeSlider?.onValueChanged.RemoveListener(OnMusicChanged);
        musicVolumeSlider?.onValueChanged.AddListener(OnMusicChanged);

        sfxVolumeSlider?.onValueChanged.RemoveListener(OnSfxChanged);
        sfxVolumeSlider?.onValueChanged.AddListener(OnSfxChanged);

        qualityDropdown?.onValueChanged.RemoveListener(OnQualityChanged);
        qualityDropdown?.onValueChanged.AddListener(OnQualityChanged);

        resolutionDropdown?.onValueChanged.RemoveListener(OnResolutionChanged);
        resolutionDropdown?.onValueChanged.AddListener(OnResolutionChanged);

        fullscreenToggle?.onValueChanged.RemoveListener(OnFullscreenChanged);
        fullscreenToggle?.onValueChanged.AddListener(OnFullscreenChanged);

        sensitivitySlider?.onValueChanged.RemoveListener(OnSensitivityChanged);
        sensitivitySlider?.onValueChanged.AddListener(OnSensitivityChanged);

        invertYToggle?.onValueChanged.RemoveListener(OnInvertYChanged);
        invertYToggle?.onValueChanged.AddListener(OnInvertYChanged);

        backButton?.onClick.RemoveListener(CloseSettings);
        backButton?.onClick.AddListener(CloseSettings);

        restoreDefaultsButton?.onClick.RemoveListener(RestoreDefaults);
        restoreDefaultsButton?.onClick.AddListener(RestoreDefaults);
    }

    /// <summary>Pulls current values out of GameSettings without re-triggering the setters.</summary>
    private void RefreshFromGameSettings()
    {
        _suppressCallbacks = true;

        if (masterVolumeSlider != null) masterVolumeSlider.value = GameSettings.MasterVolume;
        SetVolumeLabel(masterVolumeValueText, GameSettings.MasterVolume);

        if (musicVolumeSlider != null) musicVolumeSlider.value = GameSettings.MusicVolume;
        SetVolumeLabel(musicVolumeValueText, GameSettings.MusicVolume);

        if (sfxVolumeSlider != null) sfxVolumeSlider.value = GameSettings.SfxVolume;
        SetVolumeLabel(sfxVolumeValueText, GameSettings.SfxVolume);

        if (qualityDropdown != null) qualityDropdown.value = GameSettings.QualityLevel;
        if (fullscreenToggle != null) fullscreenToggle.isOn = GameSettings.Fullscreen;

        if (resolutionDropdown != null && _resolutions != null)
        {
            int match = _resolutions.FindIndex(r =>
                r.width == GameSettings.ResolutionWidth && r.height == GameSettings.ResolutionHeight);
            resolutionDropdown.value = match >= 0 ? match : 0;
        }

        if (sensitivitySlider != null) sensitivitySlider.value = GameSettings.MouseSensitivity;
        SetSensitivityLabel(GameSettings.MouseSensitivity);

        if (invertYToggle != null) invertYToggle.isOn = GameSettings.InvertY;

        _suppressCallbacks = false;
    }

    private void BuildQualityOptions()
    {
        if (qualityDropdown == null) return;
        qualityDropdown.ClearOptions();
        qualityDropdown.AddOptions(new List<string>(QualitySettings.names));
    }

    private void BuildResolutionOptions()
    {
        if (resolutionDropdown == null) return;

        _resolutions = new List<(int width, int height)>();
        var labels = new List<string>();
        foreach (var preset in PresetResolutions)
        {
            _resolutions.Add((preset.width, preset.height));
            labels.Add($"{preset.width} x {preset.height}  ({preset.aspect})");
        }

        resolutionDropdown.ClearOptions();
        resolutionDropdown.AddOptions(labels);
    }

    private static void SetVolumeLabel(TextMeshProUGUI label, float value)
    {
        if (label != null) label.text = Mathf.RoundToInt(value * 100f) + "%";
    }

    private void SetSensitivityLabel(float value)
    {
        if (sensitivityValueText != null) sensitivityValueText.text = value.ToString("0.0") + "x";
    }

    // ---- Callbacks ----

    private void OnMasterChanged(float v)
    {
        SetVolumeLabel(masterVolumeValueText, v);
        if (_suppressCallbacks) return;
        GameSettings.SetMasterVolume(v);
    }

    private void OnMusicChanged(float v)
    {
        SetVolumeLabel(musicVolumeValueText, v);
        if (_suppressCallbacks) return;
        GameSettings.SetMusicVolume(v);
    }

    private void OnSfxChanged(float v)
    {
        SetVolumeLabel(sfxVolumeValueText, v);
        if (_suppressCallbacks) return;
        GameSettings.SetSfxVolume(v);
    }

    private void OnQualityChanged(int index)
    {
        if (_suppressCallbacks) return;
        GameSettings.SetQualityLevel(index);
    }

    private void OnResolutionChanged(int index)
    {
        if (_suppressCallbacks) return;
        if (_resolutions == null || index < 0 || index >= _resolutions.Count) return;
        var res = _resolutions[index];
        GameSettings.SetResolution(res.width, res.height);
    }

    private void OnFullscreenChanged(bool value)
    {
        if (_suppressCallbacks) return;
        GameSettings.SetFullscreen(value);
    }

    private void OnSensitivityChanged(float v)
    {
        SetSensitivityLabel(v);
        if (_suppressCallbacks) return;
        GameSettings.SetMouseSensitivity(v);
    }

    private void OnInvertYChanged(bool value)
    {
        if (_suppressCallbacks) return;
        GameSettings.SetInvertY(value);
    }

    // ---- Buttons ----

    private void RestoreDefaults()
    {
        GameSettings.ResetToDefaults();
        RefreshFromGameSettings();
    }

    public void CloseSettings()
    {
        GameSettings.SaveAll();
        if (settingsPanelRoot != null) settingsPanelRoot.SetActive(false);
        if (mainButtonsPanel != null) mainButtonsPanel.SetActive(true);
    }
}
